export type LayoutType = 'single' | 'split-left' | 'split-right' | 'header-band' | 'two-column';
export type Category = 'Modern' | 'Professional' | 'Creative' | 'ATS';

export interface TemplateMetadata {
    id: string;
    name: string;
    category: Category;
    layout: LayoutType;
    description: string;
    tags: string[];
    premium?: boolean;
    defaultAccent: string;
    previewColors: { primary: string; secondary: string; bg: string; };
    hasPhoto: boolean;
}

export const TEMPLATES_LIBRARY: TemplateMetadata[] = [
    {
        id: 'classic',
        name: 'Classic Professional',
        category: 'Professional',
        layout: 'single',
        description: 'Timeless single-column layout with centered header',
        tags: ['popular', 'clean', 'traditional'],
        defaultAccent: '#1e3a5f',
        previewColors: { primary: '#1e3a5f', secondary: '#64748b', bg: '#ffffff' },
        hasPhoto: true,
    },
    {
        id: 'modern-split',
        name: 'Modern Split',
        category: 'Modern',
        layout: 'split-left',
        description: 'Colored sidebar with photo, skills & contact info',
        tags: ['two-column', 'sidebar', 'colorful'],
        defaultAccent: '#2563eb',
        previewColors: { primary: '#2563eb', secondary: '#ffffff', bg: '#ffffff' },
        hasPhoto: true,
    },
    {
        id: 'executive',
        name: 'Executive Bold',
        category: 'Professional',
        layout: 'header-band',
        description: 'Dark header band with structured two-column body',
        tags: ['executive', 'dark-header', 'corporate'],
        defaultAccent: '#0f766e',
        previewColors: { primary: '#1e293b', secondary: '#0f766e', bg: '#ffffff' },
        hasPhoto: true,
    },
    {
        id: 'minimal',
        name: 'Minimal Clean',
        category: 'Modern',
        layout: 'single',
        description: 'Ultra-minimal with thin dividers, pure typography',
        tags: ['minimal', 'clean', 'no-color'],
        defaultAccent: '#64748b',
        previewColors: { primary: '#1e293b', secondary: '#94a3b8', bg: '#ffffff' },
        hasPhoto: false,
    },
    {
        id: 'creative-sidebar',
        name: 'Creative Sidebar',
        category: 'Creative',
        layout: 'split-right',
        description: 'Dark sidebar on the right with purple accents',
        tags: ['creative', 'sidebar', 'dark'],
        defaultAccent: '#7c3aed',
        previewColors: { primary: '#1e1b4b', secondary: '#7c3aed', bg: '#ffffff' },
        hasPhoto: true,
    },
    {
        id: 'tech-stack',
        name: 'Tech Stack',
        category: 'Modern',
        layout: 'two-column',
        description: 'Developer-focused with tech badges and progress bars',
        tags: ['developer', 'tech', 'skills'],
        defaultAccent: '#059669',
        previewColors: { primary: '#059669', secondary: '#d1fae5', bg: '#ffffff' },
        hasPhoto: true,
    },
    {
        id: 'corporate',
        name: 'Corporate',
        category: 'Professional',
        layout: 'header-band',
        description: 'Navy header with gold accents and icon sections',
        tags: ['corporate', 'navy', 'formal'],
        defaultAccent: '#b45309',
        previewColors: { primary: '#1e293b', secondary: '#b45309', bg: '#ffffff' },
        hasPhoto: true,
    },
    {
        id: 'elegant',
        name: 'Elegant Serif',
        category: 'Creative',
        layout: 'single',
        description: 'Serif typography with cream background and burgundy accents',
        tags: ['elegant', 'serif', 'classic'],
        defaultAccent: '#991b1b',
        previewColors: { primary: '#991b1b', secondary: '#fef3c7', bg: '#fffdf7' },
        hasPhoto: false,
    },
    {
        id: 'ats',
        name: 'ATS Optimized',
        category: 'ATS',
        layout: 'single',
        description: 'Plain text, zero graphics — perfect ATS score',
        tags: ['ats', 'plain', 'machine-readable'],
        defaultAccent: '#000000',
        previewColors: { primary: '#000000', secondary: '#666666', bg: '#ffffff' },
        hasPhoto: false,
    },
    {
        id: 'academic',
        name: 'Academic Fellow',
        category: 'Professional',
        layout: 'single',
        description: 'Heavy text, strict spacing for publications and CVs',
        tags: ['academic', 'cv', 'traditional'],
        defaultAccent: '#1e3a8a',
        previewColors: { primary: '#1e3a8a', secondary: '#64748b', bg: '#ffffff' },
        hasPhoto: false,
    },
    {
        id: 'swiss',
        name: 'Swiss Grid',
        category: 'Creative',
        layout: 'two-column',
        description: 'Mathematically perfect grid-based layout',
        tags: ['swiss', 'grid', 'helvetica'],
        defaultAccent: '#e60000',
        previewColors: { primary: '#e60000', secondary: '#171717', bg: '#f4f4f0' },
        hasPhoto: true,
    },
    {
        id: 'faang',
        name: 'FAANG Strict',
        category: 'ATS',
        layout: 'single',
        description: 'Exact format favored by top tech recruiters',
        tags: ['tech', 'strict', 'clean'],
        defaultAccent: '#000000',
        previewColors: { primary: '#000000', secondary: '#333333', bg: '#ffffff' },
        hasPhoto: false,
    },
    {
        id: 'timeline',
        name: 'Timeline Visualizer',
        category: 'Modern',
        layout: 'two-column',
        description: 'Connected timeline graphic for work experience',
        tags: ['timeline', 'visual', 'modern'],
        defaultAccent: '#0ea5e9',
        previewColors: { primary: '#0ea5e9', secondary: '#94a3b8', bg: '#ffffff' },
        hasPhoto: false,
    },
    {
        id: 'graphic-designer',
        name: 'Graphic Designer',
        category: 'Creative',
        layout: 'split-left',
        description: 'Bold dark mode aesthetic with premium accents',
        tags: ['dark', 'creative', 'bold'],
        defaultAccent: '#f59e0b',
        previewColors: { primary: '#f59e0b', secondary: '#18181b', bg: '#18181b' },
        hasPhoto: true,
    },
    {
        id: 'hacker',
        name: 'Hacker / Terminal',
        category: 'Creative',
        layout: 'single',
        description: 'A monospace dark-theme shell interface',
        tags: ['tech', 'terminal', 'dark'],
        defaultAccent: '#10b981',
        previewColors: { primary: '#10b981', secondary: '#0d1117', bg: '#0d1117' },
        hasPhoto: false,
    },
    {
        id: 'compact',
        name: 'Compact Two-Column',
        category: 'Professional',
        layout: 'two-column',
        description: 'Maximum density for information-heavy resumes',
        tags: ['dense', 'compact', 'professional'],
        defaultAccent: '#6366f1',
        previewColors: { primary: '#6366f1', secondary: '#f3f4f6', bg: '#ffffff' },
        hasPhoto: false,
    },
    {
        id: 'newspaper',
        name: 'Newspaper Serif',
        category: 'Creative',
        layout: 'two-column',
        description: 'Editorial layout resembling a financial newspaper',
        tags: ['editorial', 'classic', 'serif'],
        defaultAccent: '#1c1917',
        previewColors: { primary: '#1c1917', secondary: '#78716c', bg: '#fafaf9' },
        hasPhoto: false,
    },
    {
        id: 'modern-right',
        name: 'Modern Right-Split',
        category: 'Modern',
        layout: 'split-right',
        description: 'Main timeline on left, sidebar on right',
        tags: ['right-split', 'modern', 'clean'],
        defaultAccent: '#3b82f6',
        previewColors: { primary: '#f8fafc', secondary: '#3b82f6', bg: '#ffffff' },
        hasPhoto: true,
    },
    {
        id: 'startup',
        name: 'Startup Founder',
        category: 'Modern',
        layout: 'single',
        description: 'Zero fluff, heavy focus on impact metrics',
        tags: ['startup', 'clean', 'impact'],
        defaultAccent: '#8b5cf6',
        previewColors: { primary: '#8b5cf6', secondary: '#111827', bg: '#ffffff' },
        hasPhoto: false,
    },
];

export const getTemplateById = (id: string) => TEMPLATES_LIBRARY.find(t => t.id === id) || TEMPLATES_LIBRARY[0];
export const CATEGORIES: Category[] = ['Modern', 'Professional', 'Creative', 'ATS'];
